### ISSUE TITLE
Spotify freezes when switching songs too quickly.

### ISSUE THREAD

**Issue by mitromanos** [bermudalocket/MeltedCrayons#26]
**Describe the bug**
When you quick skip songs on Spotify, the app freezes and won't let you skip anymore or pause. iPhone XS Max 13.3

**To Reproduce**
1. Go to 'Spotify - Iphone XS Max
2. Skip songs fast
3. Freeze

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: 13.3 

**Additional context**

**Comment by jakeva** [comment]
Hey, just to let you know this [issue](https://github.com/bermudalocket/MeltedCrayons/issues/26#11) has already been reported. It would be best for you to just continue adding into that issue instead of creating another.

**Comment by mitromanos** [comment]
Apologies, first time using GitHub, I'll remove it and add to that. Also is
the splash screen for melted crayons supposed to come up blank on Spotify?
It's just blank on mine and sometimes melted crayons doesn't work at all

**Comment by zabinga73** [comment]
I asked the other question about this issue.

Yes, it was solved, please update the tweak

my welcome thingy is mostly blank too, unrelated issue

**Comment by jakeva** [comment]
Just to let you know, this is still not fixed on the latest version (1.0.1-2+debug).

**Comment by zabinga73** [comment]
I think i have seen the issue once on this version, so it certainly is a major improvement
